-- 1. Tabel Profiles (User Data)
create table public.profiles (
  id uuid references auth.users not null primary key,
  display_name text,
  avatar_url text,
  bio text,
  updated_at timestamp with time zone
);

alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Trigger untuk Profile Baru otomatis
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, split_part(new.email, '@', 1));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Tabel Posts (Thread & Reply)
create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id), -- Relasi ke Profile
  name text default 'Anonymous',
  subject text,
  content text not null,
  parent_id bigint references public.posts(id) on delete cascade,
  image_url text,
  image_filename text,
  image_size bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.posts enable row level security;
create policy "Public posts are viewable by everyone." on posts for select using (true);
create policy "Authenticated users can insert posts." on posts for insert with check (auth.role() = 'authenticated');
create policy "Users can delete own posts." on posts for delete using (auth.uid() = user_id);

-- 3. Tabel Likes
create table public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  post_id bigint references public.posts(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

alter table public.likes enable row level security;
create policy "Public view likes" on likes for select using (true);
create policy "Auth insert likes" on likes for insert with check (auth.uid() = user_id);
create policy "Auth delete likes" on likes for delete using (auth.uid() = user_id);

-- 4. Storage Buckets (Images & Avatars)
insert into storage.buckets (id, name, public) values ('board_images', 'board_images', true);
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true);

create policy "Images are public" on storage.objects for select using ( bucket_id = 'board_images' );
create policy "Anyone can upload images" on storage.objects for insert with check ( bucket_id = 'board_images' );

create policy "Avatars are public" on storage.objects for select using ( bucket_id = 'avatars' );
create policy "Anyone can upload avatars" on storage.objects for insert with check ( bucket_id = 'avatars' );
